version: 0.2
env:
  variables:
    hugo_version: "0.80.0"
phases:
  install:
    runtime-versions:
      golang: 1.15
    commands:
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
      - hugo --minify
  post_build:
    commands:
      - aws s3 sync --delete public/ s3://${BLOG_S3_BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${BLOG_CF_DIST_ID} --paths "/*"
