# Site settings
baseurl = "https://matsuyoshi30.github.io/"
languageCode = "ja-jp"
title = "memoyoshi"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[permalinks]
	post = "/:year/:month/:day/:filename/"
	code = "/:filename/"

[params]
	author = "memoyoshi"
	# description = "Site Description"
	# bio = "author biography"
  avatar = ""

	twitter = "matsuyoshi30"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	# disqusShortname = "your_disqus_short_name"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/matsuyoshi30/"
	github-square = "https://www.github.com/matsuyoshi30/"
