# Site settings
baseurl = "https://matsuyoshi30.github.io/"
languageCode = "ja-jp"
title = "memoyoshi"
theme = "hugo-zen"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters

[permalinks]
	post = "/:year/:month/:day/:filename/"
	code = "/:filename/"

[params]
	author = "memoyoshi"
  logo = "/images/icon.jpg"
  twitter = "https://twitter.com/matsuyoshi30"
