# Site settings
baseurl = "https://blog.matsuyoshi30.net/"
languageCode = "ja-jp"
title = "memoyoshi"
theme = "harbor"
hasCJKLanguage = true
pygmentsuseclasses = true
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[[menu.main]]
  name = "About"
  url = "/about/"
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/matsuyoshi30"

[params]
  mainSections = ["post"]
	author = "matsuyoshi"

  favicon = "favicon.ico"

  [params.logo]
  url = "icon.jpg"
  width = 50
  height = 50
  alt = "Logo"

  [params.icon]
  url = "favicon.ico"
