# Site settings
baseurl = "https://blog.matsuyoshi30.net/"
languageCode = "ja-jp"
title = "memoyoshi"
theme = "harbor"
hasCJKLanguage = true
pygmentsuseclasses = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[Author]
  name = "matsuyoshi30"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[[menu.main]]
  name = "About"
  url = "/about/"

[params]
  mainSections = ["post"]

  favicon = "favicon.ico"

  [params.logo]
  url = "icon.jpg"
  width = 50
  height = 50
  alt = "Logo"

  [params.icon]
  url = "favicon.ico"
